version: '3.5'

volumes:
  redis-data:
  redis-conf:
  dbdata:
    name: backend_dbdata
    external: true

services:
  redis:
    container_name: neofelis-redis
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASS:-fiQYfvMSGww}
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  backend:
    container_name: neofelis-backend
    image: neofelis-backend
    restart: always
    depends_on:
      - timescale
    build:
      context: .
    env_file: ./.env
    ports:
      - 8080:8080
  timescale:
    container_name: neofelis-timescale
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: masterkey_postgres
      POSTGRES_DB: neofelis
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: neofelis-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "beno.dresch@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "masterkey_pgadmin"
